name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag waffle

    - name: Compile without optional dependencies
      run: docker run --env MIX_ENV=prod --env MIX_BUILD_PATH=/tmp/waffle-no-optional waffle mix compile --no-optional-deps --warnings-as-errors

    - name: Run linters
      run: docker run waffle mix credo --strict

    - name: Run tests
      run: docker run waffle mix test
